### PR TITLE
Implement husky and lint-staged for git hook. 

### LINKED ISSUE #59: Implement pre-commit hook. Either precommit or husky.
This repo contains eslint but even if contributor tries to push changes with lint error, they are able to do that. One better way could be preventing contributors from making any push unless lint issue is resolved

@warriordog, LMK If you think this implementation would be fruitful to the repo, I can work on this. otherwise you can close this.

### PR DESCRIPTION
**Pull request by Vhndaree**
fixes #59

Contributors are able to make commit even if code fails build and lint, this commit implement hook which prevent contributor from making commit unless all lint and build pass.

### CODE REVIEW

**Comment by warriordog** [comment]
Thank you! Before I merge this, I have a question. Do you think Husky is a better option than pre-commit? I didn't realize until now that pre-commit hasn't been updated in a while (a few years). It also may have issues with uninstalling or changing hooks on some newer versions of NPM. I've never used Husky, but what I'm reading suggests that it doesn't have these issues. It also seems to be much more commonly used than pre-commit. Do you have any experience with husky, and if so do you think it would be a better option?

**Comment by Vhndaree** [comment]
@warriordog Yeah you are right husky is more preferred hook than pre-commit. Husky has more reliable dev community.
But pre-commit is more lighter tool with only 3 dependencies whereas husky has more dependencies.

https://npmcompare.com/compare/husky,pre-commit, 
You can find more ways n above link.
Implementation wise there is no any complexity in both the tools, I appreciate if you decide which tool should I use for the project. And I will work on implementation afterwards.

**Comment by Vhndaree** [comment]
And one more thing,if we use husky we can use another tool lint-staged which makes error and success result in prettier format in the cli.
But, since we will use these packages as dev dependencies. I think there won’t be any breaking issues in production env

**Comment by warriordog** [comment]
@Vhndaree Thanks for the info. I think Husky would be a better choice. I usually prefer to minimize dependencies, but since this is a devDependency it doesn't really matter. In every other way Husky seems to be better, and like you said it enables lint-staged which is another useful tool.

**Comment by Vhndaree** [comment]
@warriordog prevoius commit is reverted and husky with lint-staged is used instead

**Comment by warriordog** [comment]
@Vhndaree Thank you! I'll merge this soon.

**Pull request merged**
