### PR TITLE
Fixed #68 sorted header order and downsized h1-h6 font size

### LINKED ISSUE #68: Docs: headers are not in evenly-descending order
In the documentation site, header classes (h1, h2, h3, etc) currently skip from h1 or h2 straight to h5. These h5s need to be changed to h3s, but the site CSS should be adjusted so that h3 looks like h5 currently does. h4, h5, and h6 will also need to downsized appropriately, so that all the header classes are smaller / less attention-grabbing than the previous one.

### PR DESCRIPTION
**Pull request by cnp96**
@warriordog Please help review this.

### CODE REVIEW

**Review by warriordog — APPROVED** [review]
Looks good!

**Comment by warriordog** [comment]
@cnp96 Thanks for this contribution! I'll merge it in just a moment.

**Comment by warriordog** [comment]
@cnp96 For future reference, its good practice to link issues to the pull request where they are fixed. This will trigger them to automatically close when the PR is merged, and GitHub creates links between the issue(s) and PR where they are merged. You can do this one of two ways:

- Use the "linked issues" panel in the Pull Request UI
- Add "closes #issue_number" or "fixed #issue_number" to the end of your commit message.

**Comment by cnp96** [comment]
Sure, thanks for the tip 😃

**Pull request merged**
